# decrypt
F=open("D.out",mode='r')
d=int(F.read(),16)
F.close()
F=open("N.out",mode='r')
n=int(F.read(),16)
F.close()
F=open("signature.out",mode='r')
s=int(F.read(),16)
F.close()
F=open("ans.out",mode='w')
ans=hex(pow(s,d,n))
ans=ans[2:].upper()
F.write(ans)
F.close()
