# encrypt
F=open("E.out",mode='r')
e=int(F.read(),16)
F.close()
F=open("N.out",mode='r')
n=int(F.read(),16)
F.close()
F=open("hash.in",mode='r')
h=int(F.read(),16)
F.close()
F=open("signature.out",mode='w')
secret=hex(pow(h,e,n))
secret=secret[2:].upper()
F.write(secret)
F.close()
